---
- hosts: all
  name: Creación de RDQM
  become_user: mqm
  tasks:
    - name: 'Copiar y rellenar template crtrdqm.sh'
      ansible.builtin.template:
        src: ./authorized_user.sh
        dest: /var/mqm/authorized_user.sh
        owner: mqm
        group: mqm
        mode: u=rwx,g=rwx,o=rwx
    - name: Ejecutar comandos de autorización
      ansible.builtin.command:
        cmd: "/var/mqm/authorized_user.sh"
      register: command
...
