---
- hosts: all
  tasks:
    - template:
        src: ./crtrdqm.sh 
        dest: /home/rdqmadmin/mqsc.sh
        owner: rdqmadmin
        group: mqm
        mode: u=rwx,g=rw
    - command:
        cmd: "sh /home/rdqmadmin/mqsc.sh"
      become_user: rdqmadmin
    - firewalld:
        port: "{{puerto}}"/tcp
        state: enabled
        immediate: true
        permanent: true
...
