---
- hosts: all
  tasks:
    - command:
        cmd: "/opt/mqm/bin/crtmqm -sxs -fs {{tam_m}}M {{nombre_gestor_colas}}"
      when: inventory != rdqm_hostname
- hosts: all
  tasks:
    - template:
        src: ./crtrdqm.sh 
        dest: /home/rdqmadmin/mqsc.sh
        owner: rdqmadmin
        group: mqm
        mode: u=rwx,g=rwx,o=rwx
      when: inventory == rdqm_hostname 

#   - service:
#        name: firewalld
#        state: started
#        enabled: true

#    - command:
#        cmd: "sh /opt/mqm/samp/rdqm/firewalld/configure.sh"

    - command:
        cmd: "sh /home/rdqmadmin/mqsc.sh"
      become_user: rdqmadmin
      when: inventory == rdqm_hostname

    - firewalld:
        port: "{{puerto}}/tcp"
        state: enabled
        immediate: true
        permanent: true
...
