---
- hosts: all
  name: Creaci贸n y autorizaci贸n de usuario {{ user }}
  vars:
    nombre_gestor_colas: aaaaaa
    ip_flotante: xx.xx.xx.xx
    puerto: yy
    interfaz: ensZZ
    canal_de_conexion: SYSTEM.ADMIN.SVRCONN
    usuario: alice
    uid: 1010
    password: 123
    primario: mqslaveprd01.itau.com.py
  tasks:
    - name: 'Creaci贸n usuario {{ usuario }}'
      ansible.builtin.user:
        name: "{{ usuario }}"
        shell: /bin/bash
        uid: "{{ uid }}"
        password: "{{ password | password_hash('sha512') }}"
    - name: 'Copiar y rellenar template auth.sh'
      ansible.builtin.template:
        src: ./auth.sh
        dest: /home/rdqmadmin/auth.sh
        owner: rdqmadmin
        group: mqm
        mode: u=rwx,g=rwx,o=rwx
      when: inventory_hostname == primario
    - name: 'Ejecutar comandos de autorizaci贸n administrativa para {{ usuario }}'
      ansible.builtin.command:
        cmd: "/home/rdqmadmin/auth.sh"
      become: true
      become_user: rdqmadmin
      register: command
      changed_when: command.rc != 0
      when: inventory_hostname == primario
...
