# Configuración de nodos
principal_hostname: rdqm-node-3
contingencia_hostname: rdqm-node-6
interfaz: ens192
nombre_grupo_dr: DR1
habilitar_firewall: false

# Configuración gestor de colas
nombre_gestor_colas: QM.CANCUN
ip_flotante: 192.168.238.238
puerto: 10009
tam_m: 128
puerto_dr: 7018
canal_de_conexion: SYSTEM.ADMIN.SVRCONN
usuario: mquser

# Variables estáticas ### NO TOCAR ###
dr_contingencia_ips: "\
{{ hostvars[ansible_play_hosts_all[0]].rdqm_dr_replication_contingencia }},\
{{ hostvars[ansible_play_hosts_all[1]].rdqm_dr_replication_contingencia }},\
{{ hostvars[ansible_play_hosts_all[2]].rdqm_dr_replication_contingencia }}"
dr_principal_ips: "\
{{ hostvars[ansible_play_hosts_all[0]].rdqm_dr_replication_principal }},\
{{ hostvars[ansible_play_hosts_all[1]].rdqm_dr_replication_principal }},\
{{ hostvars[ansible_play_hosts_all[2]].rdqm_dr_replication_principal }}"