---
- name: Creación de DR/HA RDQM en sitios local y remoto
  hosts: all
  vars_files:
    - config.yaml
  tasks:
    - name: 'Creación QM principal en sitio local'
      when: inventory_hostname == local_hostname
      block:
        - name: 'Copiar y rellenar template drha_crtrdqm-local.sh a sitio local'
          ansible.builtin.template:
            src: drha_crtrdqm-local.sh
            dest: /home/rdqmadmin/mqsc.sh
            owner: rdqmadmin
            group: mqm
            mode: u=rwx,g=rwx,o=rwx
        - name: 'Crear QM y ejecutar comandos de autorización en sitio local'
          command:
            cmd: "/home/rdqmadmin/mqsc.sh"
          become: true
          become_user: rdqmadmin
    - name: 'Creación QM principal en sitio remoto'
      when: inventory_hostname == remote_hostname
      block:
        - name: 'Copiar y rellenar template drha_crtrdqm-remote.sh a sitio remoto'
          ansible.builtin.template:
            src: drha_crtrdqm-remote.sh
            dest: /home/rdqmadmin/mqsc.sh
            owner: rdqmadmin
            group: mqm
            mode: u=rwx,g=rwx,o=rwx
        - name: 'Crear QM y ejecutar comandos de autorización en sitio remoto'
          command:
            cmd: "/home/rdqmadmin/mqsc.sh"
          become: true
          become_user: rdqmadmin
    - name: Habilitar puerto {{ puerto }} en firewall si se permitió
      when: habilitar_firewall
      block:
        - name: Habilitar puerto
          ansible.posix.firewalld:
            port: "{{ puerto }}/tcp"
            state: enabled
            immediate: true
            permanent: true
...
